version: '3'
services:
  web:
    image: nginx
    container_name: web
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=www.ictkiso.internal
      - NGINX_PORT=80
    volumes:
      - ~/www:/usr/share/nginx/html/

  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9-container
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND9_USER=bind
      - TZ=Asia/Tokyo
    volumes:
      - ./bind/config:/etc/bind
      - ./bind/records:/var/lib/bind
